### ISSUE TITLE
更新 STC Pay 的限额

### ISSUE THREAD

**Issue by ifsheldon** [guochengqian/KAUSTian_Handbook_CN#21]
实测，目前SABB 的卡通过 debit 每天最多能转 5K sar 到 STC Pay 账号上；通过SADAD，SABB App 上的提醒是每天可以转 60K 来 pay bill

**Comment by ijayden-lung** [comment]
你可能搞错了，通过方法2和方法3，一天转2万沙没毛病的，你再试试

**Comment by guochengqian** [comment]
> 实测，目前SABB 的卡通过 debit 每天最多能转 5K sar 到 STC Pay 账号上；通过SADAD，SABB App 上的提醒是每天可以转 60K 来 pay bill

okay，对不起 @ijayden-lung 我把他的ISSUE看错了，并且误导了你。 
他给我们提供了详情，通过方法一，SABB卡只能转5000沙。通过 方法二和三，SABB可能可以转 6万沙。

谢谢信息 @ifsheldon
