### ISSUE TITLE
加一个校内理发相关的内容？

### ISSUE THREAD

**Issue by jerrylususu** [guochengqian/KAUSTian_Handbook_CN#32]
大类上应该归在「生活」，但是感觉单独开一个二级页面又太大了？大概单独开一个「生活/其他」会好一些？

其实只是想加一个男士理发店的预约连接：http://www.envisiongo.com/a/asfourbarbershop-kaust/

**Comment by guochengqian** [comment]
开个服饰搭配 section 如何？

**Comment by jerrylususu** [comment]
感觉是个不错的选择...但是感觉点开之后发现只有一个理发的链接会不会太空了？或者先开一个其他/杂项页面，然后定期看其中的内容有没有足够到开一个新的子页面的程度？

**Comment by jerrylususu** [comment]
好，那我先试着添加一下

**Comment by jerrylususu** [comment]
在 PR #33 中加入
