### ISSUE TITLE
有没有人发一下shopping list 里面的地点

### ISSUE THREAD

**Issue by ijayden-lung** [guochengqian/KAUSTian_Handbook_CN#38]
比如图瓦小渔村的google maps或者maps.me链接。

**Comment by frankchen121212** [comment]
https://maps.app.goo.gl/Y35SBtQY8Bc5W8S28

这个是觉晓的Google map标记地点，里面有图瓦，吉达以及挺多别的地方的收藏地点，了解一下？😃😃

**Comment by guochengqian** [comment]
这个牛逼，我问问觉晓看能不能加入到 这个手册里
