### ISSUE TITLE
（插图相关？）更新图书馆 Study Room 布局信息

### ISSUE THREAD

**Issue by jerrylususu** [guochengqian/KAUSTian_Handbook_CN#56]
期中将近，如果要在图书馆为多人预约空间复习，人不在图书馆的话，很难确定到底哪几间是多人的 Study Room，因此制作示意图如下。但是不太确定如果直接编辑，图片应该如何存放？存放在外部图床，还是直接在现有文件架构内增加一个 assets 文件夹存储静态资源？

![image](https://user-images.githubusercontent.com/17522475/135710868-de7c60a7-e196-4b9d-b3bf-520f2681aa47.png)

**Comment by guochengqian** [comment]
感谢 非常有用。
所有图片放在这个位置： https://github.com/guochengqian/KAUSTian_Handbook_CN/tree/main/docs/_static/image

这次我先帮你处理吧。

**Comment by guochengqian** [comment]
已添加
