### ISSUE TITLE
沙特投资指南（2020年版）

### ISSUE THREAD

**Issue by Aaron-lujs** [guochengqian/KAUSTian_Handbook_CN#62]
[沙特投资指南.pdf](https://github.com/guochengqian/KAUSTian_Handbook_CN/files/8107281/default.pdf)
商务部国际贸易经济合作研究院
中国驻沙特阿拉伯王国大使馆经济商务处
商务部对外投资和经济合作司

**Comment by guochengqian** [comment]
这个pdf有官方链接吗？ 我们可以把官方链接加到 指南里，这样 以后这个pdf更新了，大家也能看到最新版

**Comment by Aaron-lujs** [comment]
沙特阿拉伯 (mofcom.gov.cn)
<http://www.mofcom.gov.cn/dl/gbdqzn/upload/shatealabo.pdf>
Prof. Jingsheng LU
Guangzhou Institute of Energy Conversion, The Chinese Academy of Sciences,
P. R. China,


Guocheng Qian 钱国成 ***@***.***> 于2022年6月4日周六 11:04写道：

**Comment by guochengqian** [comment]
谢谢
