### ISSUE TITLE
学校的pet control会定期给各家后院提供免费的除蚊服务 ）是pest control吗

### ISSUE THREAD

**Issue by LukeLIN-web** [guochengqian/KAUSTian_Handbook_CN#64]

**Comment by guochengqian** [comment]
请问这一个信息具体在哪里，我更正一下

**Comment by LukeLIN-web** [comment]
> 请问这一个信息具体在哪里，我更正一下
https://github.com/guochengqian/KAUSTian_Handbook_CN/blob/main/docs/content/basic/list.rst
电蚊香那里

**Comment by guochengqian** [comment]
谢谢。 已经修正。 添加了一个学校的链接： https://communitylife.kaust.edu.sa/services/housing-guest-services/service-partners/pest-control-waste-management

没问题的话，我close这个issue了
