### ISSUE TITLE
医疗方向的薅羊毛指南

### ISSUE THREAD

**Issue by shijianjian** [guochengqian/KAUSTian_Handbook_CN#65]
希望更新一下BUPA的羊毛攻略，有哪些可以弄的。

现在略有耳闻的有：
- 每年11月更新BUPA预算
- 眼镜报销，2000SAR/y？
- 看牙，4000SAR/y？

**Comment by guochengqian** [comment]
看有没有 人愿意把 bupa官网的信息更新过来吧，我先留个官网链接上去
