### ISSUE TITLE
新生物品更新

### ISSUE THREAD

**Issue by LukeLIN-web** [guochengqian/KAUSTian_Handbook_CN#66]
1. 理发工具, 刮胡刀. 理发 大约50人民币? 是否必须携带. 
2.路由器宿舍会发给你? 为什么必须带路由器
3. 想问问要不要带冬天的厚衣服?

**Comment by guochengqian** [comment]
攻略是社区写的，每个人看法可能不一样

1. 想带就带，理发校内50沙，校外25沙，和国内差不多价
2. 不知道 我们当年不发
3. 不需要
