### ISSUE TITLE
音乐中的网易云音乐解锁仓库已无法使用

### ISSUE THREAD

**Issue by 626619403** [guochengqian/KAUSTian_Handbook_CN#70]
由于网易云现版本并不会因为https访问返回空信息而降级使用http协议，故拦截已经无效。建议换成QQ音乐或其他音乐软件。

**Comment by damaoooo** [comment]
已更新仓库名单，需要自签https证书

**Comment by guochengqian** [comment]
🉑， 可以关闭这个issue了？ @damaoooo
